'use client'
import Link from 'next/link'
import { useQuery } from '@tanstack/react-query'
import { Headphones, PackageSearch, UsersRound } from 'lucide-react'
import { api } from '@/lib/api'
import type { Team, User } from '@/lib/types'
import { SubscriptionCard } from '@/components/subscription-card'
import { EmptyState, ErrorState, PageSkeleton } from '@/components/ui'
export default function Dashboard(){const me=useQuery({queryKey:['me'],queryFn:()=>api<User>('/api/me')});const teams=useQuery({queryKey:['teams'],queryFn:()=>api<Team[]>('/api/teams')});if(me.isLoading||teams.isLoading)return <PageSkeleton/>;if(me.isError||teams.isError){const error=me.error||teams.error;return <main className="page"><ErrorState message={error instanceof Error?error.message:undefined} retry={()=>{me.refetch();teams.refetch()}}/></main>}const team=teams.data?.[0];const subscriptions=team?.subscriptions.filter(s=>s.status!=='none'&&s.status!=='rejected')||[];const firstName=(me.data?.fio||me.data?.username||'друг').split(' ')[0];return <main className="page"><p className="muted text-sm">Добро пожаловать в HUB</p><h1 className="mt-1 text-[28px] font-extrabold tracking-[-.03em]">Привет, {firstName} 👋</h1>{team&&<Link href={`/teams/${team.id}`} className="card mt-6 flex items-center justify-between px-5 py-4"><div><p className="muted text-xs">Текущая команда</p><p className="mt-1 font-bold">{team.name}</p></div><span className="text-[#e43d82]">Открыть →</span></Link>}<section className="mt-8"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">Ваши подписки</h2><Link href="/catalog" className="text-xs font-bold text-[#e43d82]">Все продукты</Link></div>{subscriptions.length?<div className="space-y-3">{subscriptions.map(s=><SubscriptionCard key={s.productId} subscription={s}/>)}</div>:<EmptyState title="Нет активных подписок" description="Выберите подходящий продукт в каталоге HUB." action={<Link className="accent-button" href="/catalog">Перейти в каталог</Link>}/>}</section><section className="mt-8"><h2 className="mb-4 text-xl font-bold">Быстрые действия</h2><div className="grid grid-cols-2 gap-3">{[[team?`/teams/${team.id}`:'/teams','Команда',UsersRound],['/catalog','Каталог',PackageSearch],['/support','Поддержка',Headphones]].map(([href,label,Icon])=><Link key={label as string} href={href as string} className="card flex min-h-24 flex-col justify-between p-4"><Icon className="text-[#e43d82]" size={22}/><span className="font-bold">{label as string}</span></Link>)}</div></section></main>}
