'use client'
import Link from 'next/link'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ChevronRight, MessageCircleMore, Plus } from 'lucide-react'
import { api } from '@/lib/api'
import type { Conversation } from '@/lib/types'
import { haptic } from '@/lib/telegram'
import { EmptyState, ErrorState, PageSkeleton, PageTitle } from '@/components/ui'
/* eslint-disable @next/next/no-location-assign-relative-destination */
export default function SupportPage(){const client=useQueryClient();const query=useQuery({queryKey:['support'],queryFn:()=>api<Conversation[]>('/api/support/conversations')});const create=useMutation({mutationFn:()=>api<Conversation>('/api/support/conversations',{method:'POST',body:'{}'}),onSuccess:async conversation=>{haptic('success');await client.invalidateQueries({queryKey:['support']});window.location.href=`/support/${conversation.id}`}});if(query.isLoading)return <PageSkeleton/>;return <main className="page"><div className="flex items-start justify-between gap-4"><PageTitle eyebrow="Support Center" title="Поддержка" description="Ответы команды HUB приходят сюда и в Telegram."/><button aria-label="Новый вопрос" className="accent-button !min-h-11 !px-3" disabled={create.isPending} onClick={()=>create.mutate()}><Plus size={19}/></button></div>{create.isError&&<p className="mb-4 rounded-xl bg-red-400/10 p-3 text-sm text-red-300">{create.error.message}</p>}{query.isError?<ErrorState retry={()=>query.refetch()}/>:query.data?.length?<div className="space-y-3">{query.data.map(item=><Link key={item.id} href={`/support/${item.id}`} className="card flex items-center gap-4 p-4"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-[#2b1821] text-[#e43d82]"><MessageCircleMore/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="font-bold">Поддержка HUB</p><span className={`h-2 w-2 rounded-full ${item.status==='open'?'bg-emerald-400':'bg-zinc-600'}`}/></div><p className="muted mt-1 text-xs">{item.status==='open'?'Диалог открыт':'Диалог завершён'} · {new Intl.DateTimeFormat('ru',{day:'numeric',month:'short'}).format(new Date(item.updatedAt))}</p></div><ChevronRight size={18} className="text-zinc-600"/></Link>)}</div>:<EmptyState title="Нет обращений" description="Создайте диалог — сообщение попадёт в Telegram-топик поддержки." action={<button className="accent-button" onClick={()=>create.mutate()} disabled={create.isPending}>Новый вопрос</button>}/>}</main>}
