'use client'
import { FormEvent, useEffect, useRef, useState } from 'react'
import { useParams } from 'next/navigation'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { FileText, ImageIcon, Send, Video } from 'lucide-react'
import { api } from '@/lib/api'
import type { Conversation, SupportMessage } from '@/lib/types'
import { haptic } from '@/lib/telegram'
import { useToast } from '@/components/toast'
import { ErrorState, PageSkeleton } from '@/components/ui'
function Bubble({message}:{message:SupportMessage}){const mine=message.senderType==='user';return <div className={`flex ${mine?'justify-end':'justify-start'}`}><div className={`max-w-[84%] rounded-2xl px-4 py-3 ${mine?'rounded-br-md bg-gradient-to-br from-[#d93679] to-[#b82b65]':'rounded-bl-md border border-white/[.07] bg-[#1a1a1e]'}`}>{message.text&&<p className="whitespace-pre-wrap text-sm leading-6">{message.text}</p>}{message.attachments.map((a,i)=><div key={i} className="mt-2 flex items-center gap-2 text-xs text-white/75">{a.type==='image'?<ImageIcon size={15}/>:a.type==='video'?<Video size={15}/>:<FileText size={15}/>}<span>{a.fileName||'Вложение из Telegram'}</span></div>)}<p className={`mt-1 text-right text-[10px] ${mine?'text-white/65':'text-zinc-500'}`}>{new Intl.DateTimeFormat('ru',{hour:'2-digit',minute:'2-digit'}).format(new Date(message.createdAt))}</p></div></div>}
export default function ConversationPage(){const {id}=useParams<{id:string}>();const [text,setText]=useState('');const bottom=useRef<HTMLDivElement>(null);const client=useQueryClient();const toast=useToast();const query=useQuery({queryKey:['support',id],queryFn:()=>api<Conversation>(`/api/support/conversations/${id}`),refetchInterval:15_000});const send=useMutation({mutationFn:(value:string)=>api<SupportMessage>(`/api/support/conversations/${id}/messages`,{method:'POST',body:JSON.stringify({text:value})}),onSuccess:async()=>{setText('');haptic('success');toast('Сообщение отправлено');await client.invalidateQueries({queryKey:['support',id]})},onError:()=>haptic('error')});useEffect(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),[query.data?.messages?.length]);if(query.isLoading)return <PageSkeleton/>;if(query.isError||!query.data)return <main className="page"><ErrorState retry={()=>query.refetch()}/></main>;const submit=(event:FormEvent)=>{event.preventDefault();const value=text.trim();if(value&&!send.isPending)send.mutate(value)};return <main className="flex min-h-[calc(100dvh-150px)] flex-col px-4 pb-28 pt-5"><div className="mb-5"><h1 className="text-xl font-bold">Поддержка HUB</h1><p className="muted mt-1 text-xs">{query.data.status==='open'?'Обычно отвечаем в Telegram':'Диалог завершён'}</p></div><div className="flex-1 space-y-3">{query.data.messages?.length?query.data.messages.map(message=><Bubble key={message.id} message={message}/>):<p className="muted py-12 text-center text-sm">Напишите первое сообщение</p>}<div ref={bottom}/></div>{query.data.status==='open'&&<form onSubmit={submit} className="fixed left-1/2 z-30 flex w-full max-w-[600px] -translate-x-1/2 gap-2 border-t border-white/[.06] bg-[#0d0d0f]/95 px-4 py-3 backdrop-blur-xl" style={{bottom:'calc(74px + env(safe-area-inset-bottom))'}}><textarea value={text} onChange={e=>setText(e.target.value)} rows={1} maxLength={4000} placeholder="Сообщение…" className="max-h-28 min-h-12 flex-1 resize-none rounded-2xl border border-white/[.08] bg-[#1b1b1f] px-4 py-3 text-sm outline-none focus:border-[#e43d82]/60"/><button aria-label="Отправить" disabled={!text.trim()||send.isPending} className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#e43d82] disabled:opacity-40"><Send size={19}/></button></form>}{send.isError&&<p className="fixed left-1/2 z-40 -translate-x-1/2 text-xs text-red-300" style={{bottom:'calc(150px + env(safe-area-inset-bottom))'}}>Не удалось отправить. Попробуйте снова.</p>}</main>}
