'use client'
import { useQuery } from '@tanstack/react-query'
import { useParams } from 'next/navigation'
import { Crown } from 'lucide-react'
import { api } from '@/lib/api'
import type { Team } from '@/lib/types'
import { SubscriptionCard } from '@/components/subscription-card'
import { EmptyState, ErrorState, PageSkeleton, PageTitle } from '@/components/ui'
export default function TeamPage(){const {id}=useParams<{id:string}>();const query=useQuery({queryKey:['team',id],queryFn:()=>api<Team>(`/api/teams/${id}`)});if(query.isLoading)return <PageSkeleton/>;if(query.isError||!query.data)return <main className="page"><ErrorState retry={()=>query.refetch()}/></main>;const team=query.data;return <main className="page"><PageTitle eyebrow={team.viewerRole==='owner'?'Ваша команда':'Вы участник'} title={team.name} description={[team.church,team.city].filter(Boolean).join(' · ')||'Профиль команды HUB'}/><section><h2 className="mb-4 text-lg font-bold">Подписки</h2>{team.subscriptions.length?<div className="space-y-3">{team.subscriptions.map(s=><SubscriptionCard key={s.productId} subscription={s}/>)}</div>:<EmptyState title="Подписок пока нет" description="Владелец команды может добавить продукты через Telegram-бота."/>}</section><section className="mt-8"><h2 className="mb-4 text-lg font-bold">Участники</h2><div className="card divide-y divide-white/[.06] px-4">{team.members.map((member,index)=><div key={`${member.username}-${index}`} className="flex items-center gap-3 py-4"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-gradient-to-br from-[#3a202d] to-[#20161b] font-bold text-[#f15b99]">{member.name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{member.name}</p><p className="muted truncate text-xs">{member.username?`@${member.username}`:'Telegram username не указан'}</p></div><span className="flex items-center gap-1 text-[11px] font-bold text-zinc-400">{member.role==='owner'&&<Crown size={13} className="text-[#e43d82]"/>}{member.role==='owner'?'Владелец':'Участник'}</span></div>)}</div></section></main>}
